README.md, docs/README.md, src/Mutation.ts, src/Query.ts, src/Subscription.ts, src/client.ts, src/types.ts, src/useMutation.ts, src/useQuery.ts, src/useSubscription.ts, src/utils/error.ts, src/utils/index.ts, src/utils/network.ts, src/utils/query.ts, src/utils/vnode.ts, test/mutation.spec.ts, test/query.spec.ts, test/server/setup.ts, test/server/typedSchema.ts, test/subscription.spec.ts, test/useMutation.spec.ts, test/useQuery.spec.ts, test/useSubscription.spec.ts
So far `villus` only offered basic error handling no typings for returned responses.
**tldr:**
> Breaking change, now `useQuery`, `useMutation`, `useSubscription` and `Query`, `Mutation` and `Subscription` components will no longer expose an `errors` prop/slot-prop and will instead expose a single `error` prop/slot-prop
This PR adds the ability to fully type responses returned from executing queries, mutations, and subscriptions.
You can type your queries like this:
```ts
interface Post {
id: number;
title: string;
slug: string;
isLiked: boolean;
}
interface PostQueryResponse {
posts: Post[];
}
const { data } = useQuery<PostQueryResponse>({ query: '{ posts { id title } }' });
return { data };
```
You can also type your variables:
```ts
interface Post {
id: number;
title: string;
slug: …
```
=> feat: typed responses and Errors

src/client.ts, test/client.spec.ts
This simple PR adds support for an async context function in client.
This enables other promises to be awaited before requests are made.
For example, one might need to get an access token before executing a request:
```js
const client = createClient({
url: 'https://test.com/graphql',
context: async () => {
// Get the current access token
const token = await myAuthService.getAccessToken()
return {
fetchOptions: {
headers: {
Authorization: `bearer ${token}`
}
}
};
}
});
async function run() {
// This request will first await the access token, then returned the awaited context
// before executing the graphql query, with fetchOptions that include the 
// appropriate authorization header token
const { data } = await client.executeQuery({ query: '{ posts { id title } }' });
}
```
=> feat: support async context

docs/guide/queries.md
The `errors` prop in `useQuery` was returning `undefined` even though I could see the error in the network tab. I couldn't work out why so I tested to see if it should be `error` instead and it worked. I'm not sure if the docs are wrong or if the prop is wrong. Thought I'd send a fix just encase it's the docs.
=> Fix 'errors' typo in docs

src/Provider.ts
This resolves the console warning from Vue: `[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. `
=> fix: prefer function slots for better performance

packages/villus/src/fetch.ts, packages/villus/test/server/setup.ts, packages/villus/test/useQuery.spec.ts
This addresses the case where a GraphQL API returns non 200 response when an error is encountered
closes #49
=> fix: handle non 200 error responses

packages/villus/src/index.ts
Both `useClient` and `createClient` return a `Client`, but the type can't be referenced.
I was trying to keep a reference to `client` to use both in my components and in composables, but the type wasn't exported.
=> Export `Client` type

.gitignore, docs/content/api/client.md, docs/content/api/query.md, docs/content/api/subscription.md, docs/content/api/use-query.md, docs/content/api/use-subscription.md, docs/content/guide/plugins.md, docs/content/guide/queries.md, docs/content/guide/subscriptions.md, docs/content/plugins/handle-subscriptions.md, packages/villus/src/Mutation.ts, packages/villus/src/Provider.ts, packages/villus/src/Query.ts, packages/villus/src/Subscription.ts, packages/villus/src/client.ts, packages/villus/src/handleSubscriptions.ts, packages/villus/src/index.ts, packages/villus/src/useQuery.ts, packages/villus/src/useSubscription.ts, packages/villus/src/utils/stringify.ts, packages/villus/test/helpers/observer.ts, packages/villus/test/query.spec.ts, packages/villus/test/subscription.spec.ts, packages/villus/test/useQuery.spec.ts, packages/villus/test/useSubscription.spec.ts
This PR contains minor but breaking changes, mostly prop names have been changed to have better and easier meaning.
- `lazy` prop on `useQuery` and `Query` has been renamed to `fetchOnMount` to better communicate the purpose.
- Changed the `pausing` terminology for `useQuery` and `Query` to better reflect their use, `resume` is now `watchVariables` and `pause` is now `unwatchVariables`, `isPaused` is now `isWatchingVariables`. A little verbose but clear cut.
- renamed `pause` prop name to be `paused` on both `Query` and `Subscription` components
- renamed `suspend` prop on `Query` component to `suspended` for consistency with other props.
- subscriptions have been re-implemented as a simple plugin rather than their own weird thing.
=> feat: breaking API changes

docs/components/global/Codesandbox.vue, docs/content/guide/typescript-codgen.md, package.json, packages/villus/src/cache.ts, packages/villus/src/client.ts, packages/villus/src/fetch.ts, packages/villus/src/types.ts, packages/villus/src/useMutation.ts, packages/villus/src/useQuery.ts, packages/villus/src/useSubscription.ts, packages/villus/src/utils/query.ts, yarn.lock
This PR adds support for [TypedDocumentNode](https://github.com/dotansimha/graphql-typed-document-node#how-can-i-support-this-in-my-library) for imporved DX with the [graphql code generator project](https://graphql-code-generator.com/)
The type support is added to the composition API functions and to the client API
closes #61
=> feat: support `TypedDocumentNode`

docs/content/guide/plugins.md, docs/content/plugins/batch.md, docs/content/plugins/cache.md, docs/content/plugins/dedup.md, docs/content/plugins/fetch.md, docs/content/plugins/handle-subscriptions.md, docs/content/plugins/multipart.md, packages/villus/src/client.ts, packages/villus/src/dedup.ts, packages/villus/src/index.ts, packages/villus/test/useQuery.spec.ts
This PR adds a new default plugin called `dedup` and it **"removes"** duplicate queries and re-routes the results into the currently pending one.
That means you can safely run multiple duplicate queries across your apps and not worry about excessive requets.
=> feat: dedup plugin

docs/content/guide/plugins.md, packages/batch/src/index.ts, packages/villus/src/client.ts, packages/villus/src/fetch.ts, packages/villus/src/types.ts, packages/villus/src/utils/network.ts, packages/villus/test/client.spec.ts, packages/villus/test/server/setup.ts
Added the raw response property on the Plugin context and on the `afterQuery` callback
closes #62
=> feat: context response

docs/content/api/query.md, docs/content/api/use-query.md, docs/content/guide/queries.md, packages/villus/src/Query.ts, packages/villus/src/useQuery.ts, packages/villus/test/useQuery.spec.ts
This PR adds the ability to set `isFetching` to an initial value which helps with displaying indicators.
The default value is `false`, which might cause an unintended flash of rendered content while the component is being mounted. Having the option to set it initially to `true` avoids this issues.
=> feat: initial isFetching

docs/content/guide/plugins.md
Using config caused 'prefix' to not exist, can either remove the config part or use `config.prefix`.
=> Fix error in the docs for Plugins

packages/multipart/src/index.ts
The `@villus/multipart` package does not normalize the `operation.query` sent via the network, which makes using `graphql-tag` or `TypedDocuments` not work properly with APIs that do not support AST documents (most non-apollo) servers.
This PR uses the `normalizeQuery` helper function already used in other plugins to "print" the query to string before sending it.
closes #112
=> fix: normalize the multipart queries closes #112

docs/content/guide/plugins.md
While playing around with it I found two small typos in the plugin docs.
=> fixed 2 typos in docs

packages/villus/src/index.ts
The interfaces like QueryApi has exported in useQuery.ts, but it doesn't export in villus.d.ts. because of they don't  put in index.ts (the entry file of rollup-plugin-dts). The author has explain in this issue: https://github.com/Swatinem/rollup-plugin-dts/issues/178#issuecomment-1079488734  
In some cases, QueryApi (.etc) should be export for typescript to infer type, so I add the types that exported in .ts file but not in file index.ts.
one case I come across:
```ts
import type { customizeUseQueryOpts } from './villusExtendTypes'
import { useQuery } from 'villus'
import { TaskByIdDocument, TaskByIdQueryVariables } from '@/service/queries'
export function useTaskById(
opts: customizeUseQueryOpts<TaskByIdQueryVariables>,
) {
const res = useQuery({
query: TaskByIdDocument,
...opts,
}) …
```
=> fix: add export types for villus.d.ts

packages/villus/src/client.ts, packages/villus/src/index.ts, packages/villus/src/useMutation.ts, packages/villus/src/useQuery.ts, packages/villus/src/useSubscription.ts, packages/villus/src/utils/common.ts
I'd love to use useQuery, useMutation, but we only can define it in setup. so I extended it to use outside of setup and component. The idea to extends comes from [pinia](https://pinia.vuejs.org).
I create a sampe here: https://stackblitz.com/edit/vue-9ebjy6?file=src/App.vue , and this commit should enable it.
something should be notice:
- add a new choice param(`manualClient`) in useQuery etc, to enable these function outside of component. eg: before app mounted.  We can manually send the created client to enable it.
- when useSubscription outside of setup, due to unable register beforeUnmounted, It is recommended to pause it by user.
This commit should fix https://github.com/logaretm/villus/issues/149;
hope it will be help.
=> feat: enable useQuery etc function outside of setup and outside component

packages/villus/src/useQuery.ts
If there are no variables passed to the query, or if the variables aren't watchable,
`isWatchingVariables.value` will be true, but `stopVarsWatcher` won't be defined,
causing `query.unwatchVariables()` to throw an error when called.
Setting the default value of the `isWatchingVariables` ref to `false` by default fixes
this, as it's set to true when `beginWatchVars` is called if the vars are watched.
For reference, the reason I'm calling `unwatchVariables` on a query where the 
variables aren't being watched anyway is I'm wrapping my villus queries in a hook
which stops the variables from being watched when the component isn't on
screen (I'm using ionic, it's complicated).
=> Fix bug where calling `query.unwatchVariables()` can error

packages/batch/src/index.ts
This adds the ability to use `opContext.credentials` in the batch plugin.
=> opContext.credentials in fetch object in the batch plugin

docs/astro.config.ts, docs/src/pages/api/client.mdx, docs/src/pages/api/use-mutation.mdx, docs/src/pages/api/use-query.mdx, docs/src/pages/api/use-subscription.mdx, docs/src/pages/examples/basic-query.mdx, docs/src/pages/examples/state-store-pinia.mdx, docs/src/pages/guide/mutations.mdx, docs/src/pages/guide/overview.mdx, docs/src/pages/guide/plugins.mdx, docs/src/pages/guide/queries.mdx, docs/src/pages/guide/setup.mdx, docs/src/pages/guide/subscriptions.mdx, docs/src/pages/guide/testing.mdx, docs/src/pages/guide/typescript-codgen.mdx, docs/src/pages/index.mdx, docs/src/pages/plugins/batch.mdx, docs/src/pages/plugins/cache.mdx, docs/src/pages/plugins/dedup.mdx, docs/src/pages/plugins/fetch.mdx, docs/src/pages/plugins/handle-subscriptions.mdx, docs/src/pages/plugins/multipart.mdx
- I noticed a few minor spelling and grammar mistakes, and figured I'd go through all of the documentation and fix anything else that stood out (turns out.. a lot 😄).
- Tables are also currently broken on the site (see below screenshot). A recent Astro update adds a `extendDefaultPlugins` configuration option to preserve default plugins, and only append additional plugins, however I wasn't sure the impact of upgrading Astro in regards to the site. I simply re-added the `remark-gfm` plugin (which is what Astro includes by default), to get tables working again.
And including the `remark-gfm` plugin, changes these to:
=> docs: fix tables, and various spelling/grammar issues

packages/villus/src/index.ts, packages/villus/src/useQuery.ts
This fixes the issue of  QueryExecutionOpts not being exported from villus.d.ts.
Simply changing to `export interface` would result in the interface still not being exported from the generated villus.d.ts, hence the change to a type.
=> Exported variable 'useCreateProFormaStore' has or is using name 'QueryExecutionOpts' but cannot be named.ts(4023)

docs/src/pages/api/use-subscription.mdx
Fixes the markdown for the [`use-subscription` page](https://villus.logaretm.com/api/use-subscription/#usage) and uses [the types](https://github.com/logaretm/villus/blob/3b03942b30585b0e5d2aab0456be875281fd53dd/packages/villus/src/types.ts#L81) used for the `paused` field.
=> docs: fix table markdown for use-subscription page

docs/src/pages/guide/mutations.mdx, packages/villus/src/useMutation.ts, packages/villus/test/useMutation.spec.ts
@logaretm Following https://github.com/logaretm/villus/issues/189
I did not complicate the thing by giving the possibility of having several onData hooks because, as you said, we are with mutations that are usually executed explicitly.
I think this simple addition is enough for mutations.
Feel free to edit PR as you need.
=> feat(mutation): add onData and onError hooks

packages/villus/src/useMutation.ts
Just a simple export that is needed when we want to override some data or hooks.
Example:
```
import type { Client, CombinedError, MaybeRef, MutationApi, Operation, QueryExecutionContext } from 'villus'
import { useMutation as useMutationRequeset } from 'villus'
import { isNil, omitBy } from 'lodash-es'
// NEED THIS THAT IS NOT EXPORTED ------------------------------>
interface MutationExecutionOptions<TData> {
context: MaybeRef<QueryExecutionContext>
client?: Client
clearCacheTags?: string[]
refetchTags?: string[]
onData?: (data: TData) => void
onError?: (err: CombinedError) => void
}
export function useMutation<TData = any, TVars = any>(
query: Operation<TData, TVars>['query'],
// HERE ------------------------------>
args: Partial<MutationExecutionOptions<TData>>): MutationApi<TData, …
```
=> feat(useMutation): export MutationExecutionOptions interface

packages/villus/src/useQuery.ts, packages/villus/test/useQuery.spec.ts
I noticed the following issue - when `skip` callback uses `variables` being passed in, only the default `variables` that were passed in when `useQuery` was called are checked.
```javascript
const { data, execute } = useQuery({
query: MyQueryDocument,
fetchOnMount: false,
variables: () => { id: 'invalid-id' }
skip: ({ id }) => id === 'invalid-id' 
})
```
If I try to override `variables` when using `execute`...
```javascript
execute({
variables: { 
id: "completely-valid-id" 
}
})`
```
...the query is still skipped even though the variables passed to `execute` are OK.
=> fix: make skip work when execute overrides variables
